spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/core
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: yeshenko.dto
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: {KEYKLOAK_HOST:http://localhost:8081}/auth/realms/yeshenko-personal
mongock:
  migration-scan-package: yeshenko.changelog
minio:
  bucket:
    name: device-info
  access:
    key: minioadmin
    secret: minioadmin
  url: http://localhost:9000
server:
  port: 8081


